# Generated by Django 6.0.4 on 2026-07-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomestream",
            name="recurring_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Day of month (1–31) for monthly/yearly; day of week (1=Mon…7=Sun) for weekly. Blank = unscheduled (won't appear on the calendar).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="incomestream",
            name="week_anchor",
            field=models.DateField(
                blank=True,
                help_text="Weekly only, needed when interval > 1: a date the payment occurs on, to anchor which weeks.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="incomestream",
            name="week_interval",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=1,
                help_text="Weekly only: every N weeks (2 = fortnightly). Blank behaves as 1 (every week).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="incomestream",
            name="weekend_adjust",
            field=models.CharField(
                blank=True,
                choices=[("before", "Move to Friday before"), ("after", "Move to Monday after")],
                help_text="Monthly/yearly only: shift the day if it lands on a weekend. Blank = leave it on the weekend.",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="outgoing",
            name="recurring_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Day of month (1–31) for monthly/yearly; day of week (1=Mon…7=Sun) for weekly. Blank = unscheduled (won't appear on the calendar).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="outgoing",
            name="week_anchor",
            field=models.DateField(
                blank=True,
                help_text="Weekly only, needed when interval > 1: a date the payment occurs on, to anchor which weeks.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="outgoing",
            name="week_interval",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=1,
                help_text="Weekly only: every N weeks (2 = fortnightly). Blank behaves as 1 (every week).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="outgoing",
            name="weekend_adjust",
            field=models.CharField(
                blank=True,
                choices=[("before", "Move to Friday before"), ("after", "Move to Monday after")],
                help_text="Monthly/yearly only: shift the day if it lands on a weekend. Blank = leave it on the weekend.",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="recurring_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Day of month (1–31) for monthly/yearly; day of week (1=Mon…7=Sun) for weekly. Blank = unscheduled (won't appear on the calendar).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="week_anchor",
            field=models.DateField(
                blank=True,
                help_text="Weekly only, needed when interval > 1: a date the payment occurs on, to anchor which weeks.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="week_interval",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=1,
                help_text="Weekly only: every N weeks (2 = fortnightly). Blank behaves as 1 (every week).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="weekend_adjust",
            field=models.CharField(
                blank=True,
                choices=[("before", "Move to Friday before"), ("after", "Move to Monday after")],
                help_text="Monthly/yearly only: shift the day if it lands on a weekend. Blank = leave it on the weekend.",
                max_length=6,
            ),
        ),
    ]
