# Generated by Django 6.0.4 on 2026-07-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0002_incomestream_recurring_day_incomestream_week_anchor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="calc_method",
            field=models.CharField(
                choices=[
                    ("fixed", "Fixed amount"),
                    ("split", "Salary-ratio split of destination's need"),
                    ("surplus", "Sweep source account's surplus"),
                ],
                default="fixed",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="incomestream",
            name="recurring_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Day of month (1-31) for monthly/yearly; day of week (1=Mon...7=Sun) for weekly. Blank = unscheduled (won't appear on the calendar).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="outgoing",
            name="recurring_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Day of month (1-31) for monthly/yearly; day of week (1=Mon...7=Sun) for weekly. Blank = unscheduled (won't appear on the calendar).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="recurring_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Day of month (1-31) for monthly/yearly; day of week (1=Mon...7=Sun) for weekly. Blank = unscheduled (won't appear on the calendar).",
                null=True,
            ),
        ),
    ]
