# Generated by Django 6.0.4 on 2026-08-07 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0003_transfer_calc_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomestream",
            name="recurring_month",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Yearly only: month (1-12) the payment falls in. Blank = unscheduled.", null=True
            ),
        ),
        migrations.AddField(
            model_name="outgoing",
            name="recurring_month",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Yearly only: month (1-12) the payment falls in. Blank = unscheduled.", null=True
            ),
        ),
        migrations.AddField(
            model_name="outgoing",
            name="yearly_billing",
            field=models.CharField(
                blank=True,
                choices=[
                    ("spread", "Spread evenly across every period"),
                    ("spread_to_due", "Spread across the periods left until it's due"),
                    ("due_period", "Charge in full in the period it's due"),
                ],
                default="spread",
                help_text="Yearly only: how the amount is spread across budget periods.",
                max_length=13,
            ),
        ),
        migrations.AddField(
            model_name="pot",
            name="linked_outgoing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pots_linked",
                to="budget.outgoing",
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="recurring_month",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Yearly only: month (1-12) the payment falls in. Blank = unscheduled.", null=True
            ),
        ),
    ]
