# Generated by Django 6.0.4 on 2026-08-07 23:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0004_incomestream_recurring_month_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OutgoingVariance",
        ),
    ]
