# Generated by Django 6.0.4 on 2026-04-11 21:50

from django.db import migrations, models

import core.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("currency", models.CharField(default="GBP", max_length=3)),
                (
                    "budget_mode",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                (
                    "budget_start_day",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Day of week (1-7) for weekly mode; day of month (1-31) for monthly/yearly.",
                    ),
                ),
                (
                    "require_login",
                    models.BooleanField(
                        default=False, help_text="When True, the entire app requires a Django session login."
                    ),
                ),
                (
                    "ai_provider",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("anthropic", "Anthropic (Claude)"),
                            ("openai", "OpenAI"),
                            ("ollama", "Ollama (local)"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("ai_api_key", core.fields.EncryptedCharField(blank=True, default="")),
                ("ai_model", models.CharField(blank=True, default="", max_length=100)),
            ],
            options={
                "verbose_name": "Settings",
                "verbose_name_plural": "Settings",
            },
        ),
    ]
