# Generated by Django 6.0.4 on 2026-07-13 21:23

from django.db import migrations

import core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="webhook_inbound_secret",
            field=core.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="HMAC secret external services must sign inbound webhook requests with.",
            ),
        ),
    ]
