# Generated by Django 6.0.4 on 2026-07-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_settings_webhook_inbound_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="ai_web_search",
            field=models.BooleanField(
                default=False,
                help_text="Let the AI search the web when enriching notes. Anthropic and OpenAI only — ignored by Ollama.",
            ),
        ),
    ]
