# Generated by Django 6.0.4 on 2026-07-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_settings_ai_web_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="ai_system_prompt",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Sent as a system prompt on every AI request — e.g. your location, currency, or units, so suggestions and web-searched prices make sense for you.",
            ),
        ),
    ]
